{
 "title": "DB Info",
 "tags": [ "oracle" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host_name",
    "query": "show tag values with key=\"host_name\""
   },
   {
    "name": "instance_name",
    "query": "show tag values with key=\"instance_name\" where host_name=~ /$host_name/"
   }
  ]
 },
 "panels": [
  {
   "title": "Database Role",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "DatabaseInfo",
     "query": "SELECT last(\"DATABASE_ROLE\") AS \"Database role\", last(\"OPEN_MODE\") AS \"Open mode\", last(\"STARTUP_TIME\") AS \"Startup time\", last(\"LOGINS\") AS \"Logins\", last(\"LOG_MODE\") AS \"Archivelog mode\", last(\"STATUS\") AS \"Mount Status\" FROM \"DatabaseInfo\" WHERE (\"host_name\"::tag =~ /^$host_name$/ AND \"instance_name\"::tag =~ /^$instance_name$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "DATABASE_ROLE" ], "type": "field" },
       { "params": [ "Database role" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "DatabaseInfo",
     "query": "SELECT last(\"DATABASE_ROLE\") AS \"Database role\", last(\"OPEN_MODE\") AS \"Open mode\", last(\"STARTUP_TIME\") AS \"Startup time\", last(\"LOGINS\") AS \"Logins\", last(\"LOG_MODE\") AS \"Archivelog mode\", last(\"STATUS\") AS \"Mount Status\" FROM \"DatabaseInfo\" WHERE (\"host_name\"::tag =~ /^$host_name$/ AND \"instance_name\"::tag =~ /^$instance_name$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "STATUS" ], "type": "field" },
       { "params": [ "Mount Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "FRA % USED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FRA",
     "select": [
      [
       { "params": [ "PERCENT_SPACE_USED" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TablespaceInfo",
     "select": [
      [
       { "params": [ "pct_used_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "tablespace_name::tag", "operator": "!~", "value": "/UNDO/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "!~", "value": "/TEMP/" }
     ]
    }
   ]
  },
  {
   "title": "Backup Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RMANBackup",
     "select": [
      [
       { "params": [ "INPUT_TYPE" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "backup_status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "LogMode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "DatabaseInfo",
     "query": "SELECT last(\"DATABASE_ROLE\") AS \"Database role\", last(\"OPEN_MODE\") AS \"Open mode\", last(\"STARTUP_TIME\") AS \"Startup time\", last(\"LOGINS\") AS \"Logins\", last(\"LOG_MODE\") AS \"Archivelog mode\", last(\"STATUS\") AS \"Mount Status\" FROM \"DatabaseInfo\" WHERE (\"host_name\"::tag =~ /^$host_name$/ AND \"instance_name\"::tag =~ /^$instance_name$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "LOG_MODE" ], "type": "field" },
       { "params": [ "Archivelog mode" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Startup Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "DatabaseInfo",
     "query": "SELECT last(\"DATABASE_ROLE\") AS \"Database role\", last(\"OPEN_MODE\") AS \"Open mode\", last(\"STARTUP_TIME\") AS \"Startup time\", last(\"LOGINS\") AS \"Logins\", last(\"LOG_MODE\") AS \"Archivelog mode\", last(\"STATUS\") AS \"Mount Status\" FROM \"DatabaseInfo\" WHERE (\"host_name\"::tag =~ /^$host_name$/ AND \"instance_name\"::tag =~ /^$instance_name$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "STARTUP_TIME" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Last RMAN Backup Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RMANBackup",
     "select": [
      [
       { "params": [ "STATUS" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "backup_status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Open Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "DatabaseInfo",
     "query": "SELECT last(\"DATABASE_ROLE\") AS \"Database role\", last(\"OPEN_MODE\") AS \"Open mode\", last(\"STARTUP_TIME\") AS \"Startup time\", last(\"LOGINS\") AS \"Logins\", last(\"LOG_MODE\") AS \"Archivelog mode\", last(\"STATUS\") AS \"Mount Status\" FROM \"DatabaseInfo\" WHERE (\"host_name\"::tag =~ /^$host_name$/ AND \"instance_name\"::tag =~ /^$instance_name$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "OPEN_MODE" ], "type": "field" },
       { "params": [ "Open mode" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Logins",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "DatabaseInfo",
     "query": "SELECT last(\"DATABASE_ROLE\") AS \"Database role\", last(\"OPEN_MODE\") AS \"Open mode\", last(\"STARTUP_TIME\") AS \"Startup time\", last(\"LOGINS\") AS \"Logins\", last(\"LOG_MODE\") AS \"Archivelog mode\", last(\"STATUS\") AS \"Mount Status\" FROM \"DatabaseInfo\" WHERE (\"host_name\"::tag =~ /^$host_name$/ AND \"instance_name\"::tag =~ /^$instance_name$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "LOGINS" ], "type": "field" },
       { "params": [ "Login" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Last RMAN Backup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RMANBackup",
     "select": [
      [
       { "params": [ "End Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "backup_time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "DB Size Go",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DatabaseSize",
     "select": [
      [
       { "params": [ "Database Size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Erreurs ORA-",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AlertLog_Count",
     "query": "SELECT sum(\"session_count\") FROM \"session\" WHERE (\"host_name\" =~ /^$Host$/ AND \"db_unique_name\" =~ /^$db_unique_name$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "nb_erreurs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocking Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BlockingSessions",
     "query": "SELECT sum(\"session_count\") FROM \"session\" WHERE (\"host_name\" =~ /^$Host$/ AND \"db_unique_name\" =~ /^$db_unique_name$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "BLOCKINGSESSIONSCOUNT" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Logon Current",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LogonsCurrent",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Logons Current" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Logons",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sessions",
     "query": "SELECT sum(\"session_count\") FROM \"session\" WHERE (\"host_name\" =~ /^$Host$/ AND \"db_unique_name\" =~ /^$db_unique_name$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "session_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Objects Invalides ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "OWNER::field" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "InvalidObjects",
     "select": [
      [
       { "params": [ "invalid_objects" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Opened Cursors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OpenedCursors",
     "select": [
      [
       { "params": [ "VALUE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_wait_class",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wait_class::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WaitclassMetrics",
     "select": [
      [
       { "params": [ "avg_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "wait_class", "operator": "<>", "value": "Idle" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_tablespace_name",
     "groupBy": [
      { "params": [ "tablespace_name::tag" ], "type": "tag" }
     ],
     "measurement": "TablespaceDetail",
     "select": [
      [
       { "params": [ "megs_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Taille" ], "type": "alias" }
      ],
      [
       { "params": [ "Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Taille_Max" ], "type": "alias" }
      ],
      [
       { "params": [ "megs_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Taille_Occupee" ], "type": "alias" }
      ],
      [
       { "params": [ "Pct_Used_Max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Pourcent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_file_name",
     "groupBy": [
      { "params": [ "file_name::tag" ], "type": "tag" }
     ],
     "measurement": "DatafileInfo",
     "query": "SELECT last(\"file_size\") AS \"Size\", last(\"tablepsace_name\") AS \"Tablespace\" , last(\"space_used\") AS \"Space Used\", last(\"maxsize\") AS \"Max Size\", last(\"percent_used\") AS \"Percent\" FROM \"default\".\"DatafileInfo\" WHERE (\"instance_name\"::tag =~ /^$instance_name$/ AND \"host_name\"::tag =~ /^$host_name$/) AND $timeFilter GROUP BY \"file_name\"::tag",
     "select": [
      [
       { "params": [ "tablepsace_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TBS" ], "type": "alias" }
      ],
      [
       { "params": [ "file_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Size" ], "type": "alias" }
      ],
      [
       { "params": [ "space_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Space Used" ], "type": "alias" }
      ],
      [
       { "params": [ "maxsize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Max Size" ], "type": "alias" }
      ],
      [
       { "params": [ "percent_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "%Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Tablespace % used of Max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_tablespace_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tablespace_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TablespaceDetail",
     "select": [
      [
       { "params": [ "Pct_Used_Max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Taille Tablespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_tablespace_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tablespace_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TablespaceDetail",
     "select": [
      [
       { "params": [ "megs_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_file_type",
     "groupBy": [
      { "params": [ "file_type::tag" ], "type": "tag" }
     ],
     "measurement": "DatabaseSizeDetail",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Schema Size",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "SchemaSize",
     "select": [
      [
       { "params": [ "schema_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Schema Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "SchemaSize",
     "select": [
      [
       { "params": [ "schema_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Archivelog Number/Hr",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Archivelogs",
     "query": "SELECT mean(\"avg_value\") FROM \"waitclassmetric\" WHERE (\"db_unique_name\" =~ /^$db_unique_name$/ AND \"host_name\" =~ /^$Host$/ AND \"wait_class\" <> 'Idle') AND $timeFilter GROUP BY time($__interval), \"wait_class\" fill(null)",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Archivelog Taille/Hr",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Archivelogs",
     "query": "SELECT mean(\"avg_value\") FROM \"waitclassmetric\" WHERE (\"db_unique_name\" =~ /^$db_unique_name$/ AND \"host_name\" =~ /^$Host$/ AND \"wait_class\" <> 'Idle') AND $timeFilter GROUP BY time($__interval), \"wait_class\" fill(null)",
     "select": [
      [
       { "params": [ "Taille" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Fast Recovery Area",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FRA",
     "select": [
      [
       { "params": [ "PERCENT_RECLAIMABLE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Reclaimable" ], "type": "alias" }
      ],
      [
       { "params": [ "PERCENT_SPACE_USED" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Activity 24H prior",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_wait_class",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wait_class" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WaitclassMetrics",
     "select": [
      [
       { "params": [ "avg_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "WAIT_CLASS::field", "operator": "<>", "value": "Idle" }
     ]
    }
   ]
  },
  {
   "title": "Sessions per User",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_program",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "program::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sessions",
     "select": [
      [
       { "params": [ "session_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Sessions per Machine",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_machine",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "machine::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sessions",
     "select": [
      [
       { "params": [ "session_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" },
      { "condition": "AND", "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Backup Volume",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Input Bytes",
     "measurement": "RMANBackup",
     "select": [
      [
       { "params": [ "INPUT_BYTES" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    },
    {
     "alias": "Output Bytes",
     "measurement": "RMANBackup",
     "select": [
      [
       { "params": [ "OUTPUT_BYTES" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SGA",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_component",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "component::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SGAstat",
     "select": [
      [
       { "params": [ "size_mb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$host_name$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance_name$/" }
     ]
    }
   ]
  }
 ]
}