SELECT
    sample_id,
    sample_time,
    session_id,
    session_serial#,
    session_type,
    sql_opname,
    sql_id,
    event,
    wait_class,
    wait_time,
    session_state,
    time_waited,
    blocking_session_status,
    blocking_session,
    blocking_session_serial#
FROM
    v$active_session_history
WHERE
    sample_time > current_timestamp - INTERVAL '60' SECOND